"""add expedition tables

Revision ID: 53b1667189a9
Revises: 8a77e4bd87d3
Create Date: 2026-05-17 22:50:32.587580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53b1667189a9'
down_revision: Union[str, Sequence[str], None] = '8a77e4bd87d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expeditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_battle', sa.Integer(), nullable=False),
    sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedition_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedition_battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('battle_number', sa.Integer(), nullable=False),
    sa.Column('nemesis_id', sa.Integer(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['nemesis_id'], ['nemeses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedition_mages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('mage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['mage_id'], ['breach_mages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedition_player_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('player_card_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.ForeignKeyConstraint(['player_card_id'], ['player_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expedition_player_cards')
    op.drop_table('expedition_mages')
    op.drop_table('expedition_battles')
    op.drop_table('expedition_sets')
    op.drop_table('expeditions')
    # ### end Alembic commands ###
